---
apiVersion: v1
kind: Service
metadata:
  name: tasked-app
  labels:
    app: tasked-app
spec:
  type: LoadBalancer
  selector:
    app: tasked-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
...
